# ---
# apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mynginx
# spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      run: mynginx
#  template:
#    metadata:
#      labels:
#        run: mynginx
#    spec:
#      containers:
#      - image: hans9102/frontapp:1.0
#        name: mynginx
#        ports:
#        - containerPort: 80
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: api-server
        image: hans9102/backapp:1.0
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: 3005
        - name: MONGO_URL
          value: mongodb://mongo:27017/docker-node-mongo