apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: api-server
        image: hans9102/backapp:1.0 
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: 3000
        - name: MONGO_URL
          value: mongodb://mongo:27017/docker-node-mongo


---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: back