---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
      tier: backend

  template:
    metadata:
      labels:
        app: mongo
        tier: backend

    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
          - mountPath: /mongo
            name: mongo-volume
      volumes:
      - name: mongo-volume
      # 이 AWS EBS 볼륨은 이미 존재해야 한다.
        awsElasticBlockStore:
        volumeID: "vol-0da62f36c67a29019"
        fsType: ext4

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
    tier: backend
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer
